apiVersion: v1
kind: Secret
metadata:
    name: sentinel-env
    namespace: sentinel
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:L5sQIzAL1al9CcgzhPHfPWASfjA++VWOb6vDh+sYtau5+FGlJPlbGPe8RfWsbDSrAPQZ6C7t8m8olD3yDWo=,iv:HM5/yfWDICveWPMm9/42Tf310fvQCuFMkk6l2tiLtv4=,tag:axQ6vKVD5LLys+ee+9x1yw==,type:str]
    FRED_API_KEY: ""
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:RffzLqc=,iv:HQ6H6U5cdRB39w909cKelihYQR7ZQzA9iA4N7WKR+lQ=,tag:7NHHK7gy3Sye1ujOfhKd9g==,type:str]
    GRAFANA_DB_HOST: ENC[AES256_GCM,data:IRnxlL7FcvognMPAyS3dHqDMAC12+A==,iv:ecxxU7Qmw6YxrAkXwMOJZW/kQ9/msK9PZ89S0r1z3zc=,tag:dLUcLMfBkC0QVuyCsh/kOA==,type:str]
    GRAFANA_DB_NAME: ENC[AES256_GCM,data:8LinLLqqeck=,iv:0TMFPyhceImRKzs+d8yCnSv7kL91ou5ge4SfVv6tMYU=,tag:jhjmbdatPxbRCZbDe3W2KA==,type:str]
    GRAFANA_DB_PASSWORD: ENC[AES256_GCM,data:uaWmUdnY0z12anc=,iv:uLJXgVrBvDntzyaxAhu98sfb0tcetM5Z3zYGLOfQdmU=,tag:b7LBdTrbxTRUUgQhn3RmBg==,type:str]
    GRAFANA_DB_SSLMODE: ENC[AES256_GCM,data:xPfegVxpjw==,iv:GzTEFe/RzLAj+nIbypep4EerDrs6gghBBuoD2N88CAo=,tag:7ECabvYER9TCZMbglQg77A==,type:str]
    GRAFANA_DB_USER: ENC[AES256_GCM,data:eg3vMRGYzNrcMg==,iv:QxePmA/blnllfITwJYK9s4SyE/BhfrdlUqaoiXQv9ZE=,tag:pbI/3vSLRElhAXMstrPagQ==,type:str]
    TELEGRAM_BOT_TOKEN: ""
    TELEGRAM_CHAT_ID: ""
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gqgan8hkr7469fpdwsddhx9qnhsmmxdvgm2v5f38twsntvus3gns5200tf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMnkvNUR6YTB0TkMwNXAw
            eXBkQUdQM0o5NXVVNUd3T2FpMUJiVVpiRW00ClVHWm1lL3h6azY0a2JtZmYreXZX
            RzlMSUxuS2t4S2UrMEVVUkNuME1Md1EKLS0tIFNldlo1aEExa1hPREU2ZXZ3a2hU
            aXhqQWNaa0NTandLVXhzSERDSjZWZEUKPVT/x+g6Tk8LKKi8BCKVDhLCx76WtEGU
            2cCiAixkLhCE/KaUWKpnHIBm+WL14Zy7SStFRmNOej2/rGlT0qQoMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T09:49:39Z"
    mac: ENC[AES256_GCM,data:LU3iqip49Uj7XTKHX1dX8/ZIgC05rsVchWGe0XEX9B7fSnMJRGcnwGI2Z8f/SGtBGfoHN54n02FsVc6yILgddZsPzg2VfuLG0/pXTGqSs8fu0kHqR+IV/uojqF/qR/0Eelye4aB30AyH6TF9hdb/NwOaeWeu+A0sST2rhqBHd8w=,iv:aj5gl+lS1G8vbH8auIg1Mfrtg/HH48aLxXjPSVf6tlc=,tag:S1d/uwQrIQ/nMmYWS5OHag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
